name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # ติดตั้ง Android SDK + ยอมรับ license อัตโนมัติ
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      # สร้าง Debug APK (ถ้าจะทำ Release ให้เปลี่ยนคำสั่งด้านล่าง)
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace --no-daemon

      # อัพโหลดไฟล์ APK ขึ้นเป็น Artifact ให้ดาวน์โหลดจากหน้า Actions
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: RecoverX-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
